module.exports = {
	"rules": {
		"array-bracket-newline": 0,
		"array-callback-return": 1,
		"array-element-newline": 0,
		"arrow-body-style": [1, "always"],
		"arrow-parens": 1,
		"block-spacing": 1,
		"brace-style": 1,
		"camelcase": 0,
		"callback-return": 1,
		"capitalized-comments": 0,
		"class-methods-use-this": 1,
		"comma-dangle": 1,
		"comma-spacing": 1,
		"consistent-return": 1,
		"consistent-this": 1,
		"curly": 1,
		"dot-location": [1, "property"],
		"eol-last": 0,
		"eqeqeq": 1,
		"func-names": [1, "as-needed"],
		"function-paren-newline": 0,
		"global-require": 1,
		"id-length": 0,
		"indent": [1, "tab", {"SwitchCase": 1}],
		"init-declarations": 0,
		"key-spacing": 1,
		"keyword-spacing": 1,
		"line-comment-position": 0,
		"max-len": 0,
		"max-lines": 0,
		"max-params": 0,
		"max-statements": 0,
		"multiline-comment-style": 0,
		"multiline-ternary": 1,
		"newline-per-chained-call": 0,
		"new-cap": 1,
		"no-alert": 0,
		"no-confusing-arrow": 0,
		"no-console": 1,
		"no-else-return": 1,
		"no-extra-parens": [1, "all", { "ignoreJSX": "all", "nestedBinaryExpressions": false }],
		"no-extra-semi": 1,
		"no-inline-comments": 0,
		"no-lone-blocks": 1,
		"no-lonely-if": 1,
		"no-magic-numbers": 0,
		"no-mixed-requires": 0,
		"no-mixed-spaces-and-tabs": 1,
		"no-multi-spaces": 1,
		"no-negated-condition": 0,
		"no-path-concat": 1,
		"no-plusplus": 0,
		"no-process-env": 0,
		"no-sync": 0,
		"no-tabs": 0,
		"no-ternary": 0,
		"no-trailing-spaces": 1,
		"no-undefined": 0,
		"no-undef-init": 1,
		"no-unneeded-ternary": 1,
		"no-unused-expressions": [2, {"allowShortCircuit": true, "allowTernary": true}],
		"no-useless-escape": 1,
		"no-useless-return": 1,
		"object-curly-newline": 0,
		"object-curly-spacing": [1, "always"],
		"object-property-newline": 1,
		"object-shorthand": 0,
		"one-var": 1,
		"operator-assignment": 1,
		"operator-linebreak": [1, "before", { "overrides": { "?": "after", ":": "after" } }],
		"padded-blocks": 0,
		"prefer-arrow-callback": 1,
		"prefer-const": 1,
		"prefer-destructuring": 0,
		"prefer-template": 1,
		"quotes": 1,
		"quote-props": 1,
		"require-jsdoc": 0,
		"semi": 0,
		"sort-imports": 0,
		"sort-keys": 0,
		"sort-vars": 0,
		"space-before-blocks": 1,
		"space-before-function-paren": 0,
		"space-in-parens": 1,
		"space-infix-ops": 1,
		"spaced-comment": 1,
		"space-unary-ops": 1,
		"strict": 1
	},
	"extends": "eslint:all"
}